default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: Marixuanna1990
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: metal22_ru_development

test:
  <<: *default
  database: metal22_ru_test

production:
  <<: *default
  database: metal22_ru_production
  username: metal22_ru
  password: <%= ENV['METAL22_RU_DATABASE_PASSWORD'] %>