default: &default

  adapter: postgresql

  encoding: unicode

  pool: 5

development:

  <<: *default

  database: metal22_development

  username: deploy

password: <%= ENV['metal22_DATABASE_PASSWORD'] %>

test:

  <<: *default

  database: metal22_test

  username: deploy

password: <%= ENV['metal22_DATABASE_PASSWORD'] %>

production:

  <<: *default

  database: metal22_production

  # username: metal22

  # password: <%= ENV['metal22_DATABASE_PASSWORD'] %>