 default: &default
    adapter: postgresql
    encoding: unicode
    pool: 5
    username: deploy

  development:
    <<: *default
    database:  {{ name }}_development

  test:
    <<: *default
    database:  {{ name }}_test

  production:
    <<: *default
    database:  {{ name }}_production