setup: &setup
  secret_token: <%= ENV['SECRET_TOKEN'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  admins:
    - admin@metal22.ru

development:
  <<: *setup

test:
  <<: *setup

production:
<<: *setup
